name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set GOOS and GOARCH
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build
        run: go build -v -o igitt ./cmd/igitt

      - name: Test
        run: go test -v ./...

      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: igitt-${{ matrix.goos }}-${{ matrix.goarch }}
          path: igitt
          # name: igitt-${{ matrix.goos }}-${{ matrix.goarch }}
          # path: igitt-${{ matrix.goos }}-${{ matrix.goarch }}
